-- Author
DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR
    (ID UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
     NAME VARCHAR NOT NULL UNIQUE);
-- Genre
DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE
    (ID UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
     NAME VARCHAR NOT NULL UNIQUE);
-- Book
DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK
    (ID UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
     TITLE VARCHAR,
     AUTHOR_ID UUID,
     GENRE_ID UUID);
ALTER TABLE BOOK
    ADD CONSTRAINT UNIQUE_BOOK UNIQUE(TITLE, AUTHOR_ID);
ALTER TABLE BOOK
    ADD CONSTRAINT FK_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID) ON DELETE CASCADE;
ALTER TABLE BOOK
    ADD CONSTRAINT FK_GENRE FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID)  ON DELETE CASCADE;
-- Comment
DROP TABLE IF EXISTS COMMENT;
CREATE TABLE COMMENT
    (ID UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    BODY VARCHAR,
    BOOK_ID UUID);
ALTER TABLE COMMENT
    ADD CONSTRAINT FK_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID) ON DELETE CASCADE;