SET @MONOGRAPH_ID = (SELECT ID FROM FINAL TABLE ( INSERT INTO GENRE(NAME) VALUES('Монография')));
SET @FRANK_WEBB_ID = (SELECT ID FROM FINAL TABLE ( INSERT INTO AUTHOR(NAME) VALUES('Frank Webb')));
INSERT INTO BOOK(TITLE, AUTHOR_ID, GENRE_ID) VALUES('Dynamic Composition', @FRANK_WEBB_ID, @MONOGRAPH_ID);
SET @VASILY_KANDINSKY_ID = (SELECT ID FROM FINAL TABLE ( INSERT INTO AUTHOR(NAME) VALUES('Василий Кандинский')));
SET @SOME_BOOK_ID = (SELECT ID FROM FINAL TABLE ( INSERT INTO BOOK(TITLE, AUTHOR_ID, GENRE_ID) VALUES('Точка и линия на плоскости', @VASILY_KANDINSKY_ID, @MONOGRAPH_ID)));
INSERT INTO COMMENT(BODY, BOOK_ID) VALUES('Very intresting book!', @SOME_BOOK_ID);