-- Book
DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK
    (ID UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
     TITLE VARCHAR,
     AUTHOR_ID UUID,
     GENRE_ID UUID);
ALTER TABLE BOOK
    ADD CONSTRAINT UNIQUE_BOOK UNIQUE(TITLE, AUTHOR_ID);
-- Author
DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR
    (ID UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
     NAME VARCHAR NOT NULL UNIQUE);
-- Genre
DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE
    (ID UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
     NAME VARCHAR NOT NULL UNIQUE);