SET @MONOGRAPH_ID = (SELECT ID FROM FINAL TABLE ( INSERT INTO GENRE(NAME) VALUES('Монография')));
SET @FRANK_WEBB_ID = (SELECT ID FROM FINAL TABLE ( INSERT INTO AUTHOR(NAME) VALUES('Frank Webb')));
INSERT INTO BOOK(ID, TITLE, AUTHOR_ID, GENRE_ID) VALUES('b7cba70c-379e-11ec-8d3d-0242ac130003', 'Dynamic Composition', @FRANK_WEBB_ID, @MONOGRAPH_ID);
SET @VASILY_KANDINSKY_ID = (SELECT ID FROM FINAL TABLE ( INSERT INTO AUTHOR(NAME) VALUES('Василий Кандинский')));
SET @SOME_BOOK_ID = (SELECT ID FROM FINAL TABLE ( INSERT INTO BOOK(ID, TITLE, AUTHOR_ID, GENRE_ID) VALUES('ed2463c6-f4f1-4afb-ab07-947a0929b35f', 'Точка и линия на плоскости', @VASILY_KANDINSKY_ID, @MONOGRAPH_ID)));
INSERT INTO USER(USERNAME, PASSWORD) VALUES('junior', '$2a$12$y3nlGQR9202kIT4dIMZNC.Jsmtgzk1ZdSO9MHVzECowGi5o7LEUFG');--pass=12345678
INSERT INTO USER(USERNAME, PASSWORD) VALUES('manager', '$2a$12$0cznN5TT5fg2YRO3YJ3wgu/AtbCfS6IN3yWbAMNaA/Qz1qZMW2a9m');--pass=5555
INSERT INTO USER(USERNAME, PASSWORD) VALUES('user', '$2a$12$ac9gF7d6TRmFVgNarhpqfOjSoTZFb2C.cJYdBldf8Go8ngDNHUVkG');--pass=user